begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_table('public','ai_jobs','Durable AI queue exists');
select has_function('public','enqueue_ai_job',array['uuid','text','jsonb','text']);
select ok(not has_function_privilege('service_role','public.enqueue_ai_job(uuid,text,jsonb,text)','execute'),'Enqueue reserved for authenticated users');
insert into auth.users(id,email) values
 ('16000000-0000-4000-8000-000000000001','ai-owner@paceon.example'),
 ('16000000-0000-4000-8000-000000000002','ai-foreign@paceon.example');
insert into resources(id,user_id,title,type,total_pages) select ('26000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'16000000-0000-4000-8000-000000000001','Test','BOOK',100 from generate_series(1,6) n;
create temporary table fixture as select
 '{"schemaVersion":1,"kind":"BOOK_ANALYSIS","book":{"title":"Test","authors":[],"totalPages":100,"description":""},"outline":"","facts":{"today":"2026-09-13","completedPages":0,"remainingPages":100,"progressPercent":0,"planMode":null,"forecastDate":null,"targetDate":null,"replanRequired":false,"recentLearningPages":0,"recentLearningMinutes":0,"validTimedSamples":0}}'::jsonb || jsonb_build_object('sourceRevision',repeat('a',64)) input;
create temporary table claimed(v jsonb);
grant all on fixture,claimed to authenticated,service_role;
set local role authenticated;
select set_config('request.jwt.claim.sub','16000000-0000-4000-8000-000000000001',true);
select lives_ok($$select enqueue_ai_job('26000000-0000-4000-8000-000000000001','BOOK_ANALYSIS',(select input from fixture),repeat('a',64))$$,'Owner enqueues');
select is(enqueue_ai_job('26000000-0000-4000-8000-000000000001','BOOK_ANALYSIS',(select input from fixture),repeat('a',64)),(select id from ai_jobs limit 1),'Duplicate enqueue reuses active');
select throws_ok($$update ai_jobs set status='COMPLETED'$$,'42501',null,'Browser cannot update');
select throws_ok($$insert into ai_jobs(user_id,resource_id,kind,input,source_revision) values(auth.uid(),'26000000-0000-4000-8000-000000000001','COACH','{}',repeat('a',64))$$,'42501',null,'Browser cannot insert');
select throws_ok($$select claim_ai_job()$$,'42501',null,'Browser cannot claim');
select throws_ok($$select finish_ai_job(gen_random_uuid(),gen_random_uuid(),null,null,null,null,null,'PROVIDER_ERROR')$$,'42501',null,'Browser cannot finish');
select throws_ok($$select enqueue_ai_job('26000000-0000-4000-8000-000000000002','BOOK_ANALYSIS',(select input||'{"secret":"forbidden"}' from fixture),repeat('a',64))$$,'23514','Invalid AI input','Unknown context fields rejected');
select throws_ok($$select enqueue_ai_job('26000000-0000-4000-8000-000000000002','BOOK_ANALYSIS',(select jsonb_set(input,'{facts,completedPages}','null') from fixture),repeat('a',64))$$,'23514','Invalid AI input','Null numeric facts rejected');
select throws_ok($$select enqueue_ai_job('26000000-0000-4000-8000-000000000002','BOOK_ANALYSIS',(select jsonb_set(input,'{outline}',to_jsonb(repeat('x',12001))) from fixture),repeat('a',64))$$,'23514','Invalid AI input','Oversized outline rejected');
select set_config('request.jwt.claim.sub','16000000-0000-4000-8000-000000000002',true);
select is((select count(*) from ai_jobs),0::bigint,'Foreign owner cannot read');
select throws_ok($$select enqueue_ai_job('26000000-0000-4000-8000-000000000001','BOOK_ANALYSIS',(select input from fixture),repeat('a',64))$$,'42501','Book not found','Foreign owner cannot enqueue');
reset role;
set local role anon;
select throws_ok($$select count(*) from ai_jobs$$,'42501',null,'Anonymous cannot read');
select throws_ok($$select enqueue_ai_job(gen_random_uuid(),'COACH','{}',repeat('a',64))$$,'42501',null,'Anonymous cannot enqueue');
reset role;
set local role service_role;
insert into claimed select claim_ai_job();
select is((select v->>'attempts' from claimed),'1','First claim records attempt');
select is(claim_ai_job(),null::jsonb,'Live lease is not reclaimed');
select is(finish_ai_job((select (v->>'id')::uuid from claimed),gen_random_uuid(),null,null,null,null,null,'PROVIDER_ERROR'),false,'Wrong lease cannot finish');
select throws_ok($$select finish_ai_job((select (v->>'id')::uuid from claimed),(select (v->>'lease_token')::uuid from claimed),'{}','fixture','resp_fixture',1,1,null)$$,'23514','Invalid AI result','Invalid result rejected');
select ok(finish_ai_job((select (v->>'id')::uuid from claimed),(select (v->>'lease_token')::uuid from claimed),'{"difficulty":"MODERATE","estimatedMinutes":100,"importance":"MEDIUM","confidence":0.3,"summary":"Metadata only","reasons":["Limited evidence"]}','fixture','resp_fixture',10,20,null),'Live lease completes');
select is((select input_tokens from ai_jobs limit 1),10,'Token provenance saved');
select is(finish_ai_job((select (v->>'id')::uuid from claimed),(select (v->>'lease_token')::uuid from claimed),null,null,null,null,null,'PROVIDER_ERROR'),false,'Finished lease cannot overwrite');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','16000000-0000-4000-8000-000000000001',true);
select is(enqueue_ai_job('26000000-0000-4000-8000-000000000001','BOOK_ANALYSIS',(select input from fixture),repeat('a',64)),(select (v->>'id')::uuid from claimed),'Completed revision reused');
select enqueue_ai_job('26000000-0000-4000-8000-000000000001','BOOK_ANALYSIS',(select input||jsonb_build_object('sourceRevision',repeat('b',64),'outline','Another outline') from fixture),repeat('b',64));
reset role;
set local role service_role;
select claim_ai_job();
select ok(finish_ai_job((select id from ai_jobs where source_revision=repeat('b',64)),(select lease_token from ai_jobs where source_revision=repeat('b',64)),'{"difficulty":"EASY","estimatedMinutes":80,"importance":"LOW","confidence":0.2,"summary":"Other context","reasons":["Outline"]}','fixture','resp_b',1,1,null),'Revision B completes');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','16000000-0000-4000-8000-000000000001',true);
select is(enqueue_ai_job('26000000-0000-4000-8000-000000000001','BOOK_ANALYSIS',(select input from fixture),repeat('a',64)),(select (v->>'id')::uuid from claimed),'A B A reuses original A');
select is((select source_revision from ai_jobs order by updated_at desc limit 1),repeat('a',64),'Reused A is most recently requested context');
select enqueue_ai_job(('26000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'BOOK_ANALYSIS',(select input from fixture),repeat('a',64)) from generate_series(2,6) n;
select throws_ok($$select enqueue_ai_job('26000000-0000-4000-8000-000000000001','COACH',(select input||'{"kind":"COACH"}' from fixture),repeat('a',64))$$,'PT429','AI queue full','Sixth active job denied');
reset role;
set local role service_role;
delete from claimed;
insert into claimed select claim_ai_job();
update ai_jobs set lease_expires_at=clock_timestamp()-interval '1 second' where id=(select (v->>'id')::uuid from claimed);
select is(finish_ai_job((select (v->>'id')::uuid from claimed),(select (v->>'lease_token')::uuid from claimed),null,null,null,null,null,'PROVIDER_ERROR'),false,'Expired lease cannot finish');
select is(claim_ai_job()->>'attempts','2','Expired job retried');
select is(finish_ai_job((select (v->>'id')::uuid from claimed),(select (v->>'lease_token')::uuid from claimed),null,null,null,null,null,'PROVIDER_ERROR'),false,'Old worker loses CAS after reclaim');
update ai_jobs set lease_expires_at=clock_timestamp()-interval '1 second' where id=(select (v->>'id')::uuid from claimed);
select is(claim_ai_job()->>'attempts','3','Third attempt allowed');
update ai_jobs set lease_expires_at=clock_timestamp()-interval '1 second' where id=(select (v->>'id')::uuid from claimed);
select claim_ai_job();
select is((select error_code from ai_jobs where id=(select (v->>'id')::uuid from claimed)),'WORKER_TIMEOUT','Exhausted attempts fail safely');
delete from claimed;
insert into claimed select to_jsonb(j) from ai_jobs j where status='PROCESSING' limit 1;
select ok(finish_ai_job((select (v->>'id')::uuid from claimed),(select (v->>'lease_token')::uuid from claimed),'{"secret":"must not persist"}','secret','secret',1,1,'PROVIDER_ERROR'),'Failure persisted');
select ok((select result is null and model is null and provider_response_id is null and lease_token is null from ai_jobs where id=(select (v->>'id')::uuid from claimed)),'Failure discards provider payload and clears lease');
reset role;
select lives_ok($$delete from resources where id='26000000-0000-4000-8000-000000000001'$$,'Resource cleanup cascades');
select is((select count(*) from ai_jobs where resource_id='26000000-0000-4000-8000-000000000001'),0::bigint,'Resource jobs removed');
select lives_ok($$delete from auth.users where id='16000000-0000-4000-8000-000000000001'$$,'Account cleanup cascades');
select is((select count(*) from ai_jobs),0::bigint,'Account jobs removed');
select * from finish();
rollback;
