begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values('25000000-0000-4000-8000-000000000001','speech-clock@example.test');
insert into learning_workspaces(id,user_id,title) values('25000000-0000-4000-8000-000000000002','25000000-0000-4000-8000-000000000001','Speech clock');
create temporary table tick_fixture(v jsonb);
grant all on tick_fixture to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','25000000-0000-4000-8000-000000000001',true);
insert into tick_fixture select learning_command(jsonb_build_object('action','START','requestId',gen_random_uuid(),'workspaceId','25000000-0000-4000-8000-000000000002','deviceId','25000000-0000-4000-8000-000000000003','timezone','Asia/Seoul'))->'session';
reset role;
update learning_sessions set last_seen_at=clock_timestamp()-interval '20 seconds' where user_id='25000000-0000-4000-8000-000000000001';
set local role authenticated;
select lives_ok($$select learning_speech_command((select jsonb_build_object('action','SPEECH_TICK','requestId',gen_random_uuid(),'sessionId',v->>'id','deviceId',v->>'device_id','generation',(v->>'generation')::integer,'playing',true) from tick_fixture))$$,'First speech tick starts observation');
select is((select elapsed_seconds from learning_sessions where user_id=auth.uid()),0,'First tick excludes startup wait');
reset role;
-- Move both existing observation and covered lease interval into the past.
update learning_sessions set last_seen_at=clock_timestamp()-interval '10 seconds',last_activity_at=clock_timestamp()-interval '10 seconds' where user_id='25000000-0000-4000-8000-000000000001';
set local role authenticated;
select lives_ok($$select learning_speech_command((select jsonb_build_object('action','SPEECH_TICK','requestId',gen_random_uuid(),'sessionId',v->>'id','deviceId',v->>'device_id','generation',(v->>'generation')::integer,'playing',false) from tick_fixture))$$,'Final false tick stops observation');
select ok((select elapsed_seconds between 9 and 11 from learning_sessions where user_id=auth.uid()),'Observed speech interval credited once');
select is((select status from learning_sessions where user_id=auth.uid()),'PAUSED','Upload and provider wait remain paused');
select throws_ok($$select learning_speech_command((select jsonb_build_object('action','SPEECH_TICK','requestId',gen_random_uuid(),'sessionId',v->>'id','deviceId',gen_random_uuid(),'generation',(v->>'generation')::integer,'playing',true) from tick_fixture))$$,'P0001','LEARNING_CONFLICT','Stale speech device rejected');
update tick_fixture set v=learning_command(jsonb_build_object('action','START','requestId',gen_random_uuid(),'workspaceId','25000000-0000-4000-8000-000000000002','deviceId','25000000-0000-4000-8000-000000000003','timezone','Asia/Seoul'))->'session';
reset role;
update learning_sessions set last_seen_at=clock_timestamp()-interval '8 seconds',last_activity_at=clock_timestamp()-interval '8 seconds' where user_id='25000000-0000-4000-8000-000000000001';
insert into learning_private.video_text_activity(session_id,observed_at) select (v->>'id')::uuid,clock_timestamp() from tick_fixture on conflict(session_id) do update set observed_at=excluded.observed_at;
set local role authenticated;
select learning_speech_command((select jsonb_build_object('action','SPEECH_TICK','requestId',gen_random_uuid(),'sessionId',v->>'id','deviceId',v->>'device_id','generation',(v->>'generation')::integer,'playing',true) from tick_fixture));
select ok((select elapsed_seconds between 17 and 19 from learning_sessions where user_id=auth.uid()),'Text interval is settled before switching to speech');
select learning_speech_command((select jsonb_build_object('action','SPEECH_TICK','requestId',gen_random_uuid(),'sessionId',v->>'id','deviceId',v->>'device_id','generation',(v->>'generation')::integer,'playing',false) from tick_fixture));
select is((select status from learning_sessions where user_id=auth.uid()),'ACTIVE','Recent text keeps shared session active after speech stops');
select ok((select elapsed_seconds between 17 and 19 from learning_sessions where user_id=auth.uid()),'Overlapping text and speech observations do not double count');
reset role;
select * from finish();
rollback;
