begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_table('public','learning_workspaces','Learning workspace storage exists');
select has_function('public','learning_command',array['jsonb'],'Learning command boundary exists');
insert into auth.users(id,email) values ('18000000-0000-4000-8000-000000000001','lr-owner@paceon.example'),('18000000-0000-4000-8000-000000000002','lr-other@paceon.example');
create temporary table lr_fixture(k text primary key,v jsonb);
grant all on lr_fixture to authenticated,service_role;
set local role authenticated;
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000001',true);
insert into lr_fixture values('create','{"action":"CREATE","requestId":"18000000-0000-4000-8000-000000000003","workspaceId":"28000000-0000-4000-8000-000000000001","title":"Practice","prompt":"Daily life","kind":"WRITING"}');
insert into lr_fixture select 'workspace',learning_command(v) from lr_fixture where k='create';
select is(learning_command((select v from lr_fixture where k='create')),(select v from lr_fixture where k='workspace'),'Identical command replay returns original result');
select throws_ok($$select learning_command((select v||'{"title":"changed"}' from lr_fixture where k='create'))$$,'P0001','LEARNING_CONFLICT','Reused request with changed payload conflicts');
select throws_ok($$select learning_command('{"action":"CREATE","requestId":"invalid","workspaceId":"28000000-0000-4000-8000-000000000001","title":"x","prompt":""}')$$,'P0001','LEARNING_INVALID','Malformed UUID gets safe error');
select throws_ok($$select learning_command((select v||'{"extra":true}' from lr_fixture where k='create'))$$,'P0001','LEARNING_INVALID','Unknown fields rejected directly at RPC');
select throws_ok($$select learning_command((select v||'{"prompt":null}' from lr_fixture where k='create'))$$,'P0001','LEARNING_INVALID','Null string rejected');
select lives_ok($$select learning_command('{"action":"SAVE_DRAFT","requestId":"18000000-0000-4000-8000-000000000004","workspaceId":"28000000-0000-4000-8000-000000000001","expectedVersion":0,"draft":"I went home."}')$$,'Draft CAS succeeds');
select throws_ok($$select learning_command('{"action":"SAVE_DRAFT","requestId":"18000000-0000-4000-8000-000000000005","workspaceId":"28000000-0000-4000-8000-000000000001","expectedVersion":0,"draft":"overwrite"}')$$,'P0001','LEARNING_CONFLICT','Stale draft cannot overwrite');
select throws_ok($$update learning_messages set content='overwrite'$$,'42501',null,'Messages are immutable to browser');
select throws_ok($$update learning_workspaces set draft='bypass'$$,'42501',null,'Workspace writes must use CAS RPC');
select throws_ok($$select input from learning_ai_jobs$$,'42501',null,'Internal job input not browser readable');
select throws_ok($$select claim_learning_job()$$,'42501',null,'Browser cannot claim worker job');
insert into lr_fixture values('start',jsonb_build_object('action','START','requestId',gen_random_uuid(),'workspaceId','28000000-0000-4000-8000-000000000001','deviceId','38000000-0000-4000-8000-000000000001','timezone','Asia/Seoul'));
insert into lr_fixture select 'session',learning_command(v)->'session' from lr_fixture where k='start';
select throws_ok($$select learning_command((select v||jsonb_build_object('requestId',gen_random_uuid(),'deviceId','38000000-0000-4000-8000-000000000002') from lr_fixture where k='start'))$$,'P0001','LEARNING_CONFLICT','Second device cannot start live session');
insert into lr_fixture select 'event',jsonb_build_object('action','HEARTBEAT','requestId',gen_random_uuid(),'sessionId',v->>'id','deviceId',v->>'device_id','generation',(v->>'generation')::integer,'activity',true) from lr_fixture where k='session';
reset role;
-- Simulate server clock observations without trusting any client duration.
update learning_sessions set last_seen_at=clock_timestamp()-interval '20 seconds',last_activity_at=clock_timestamp()-interval '20 seconds' where user_id='18000000-0000-4000-8000-000000000001';
set local role authenticated;
select learning_command((select v from lr_fixture where k='event'));
select ok((select elapsed_seconds between 20 and 21 from learning_sessions),'Heartbeat accrues server-observed interval');
select learning_command((select v||jsonb_build_object('action','PAUSE','reason','MANUAL','requestId',gen_random_uuid()) from lr_fixture where k='event'));
reset role;
update learning_sessions set last_seen_at=clock_timestamp()-interval '5 minutes' where user_id='18000000-0000-4000-8000-000000000001';
set local role authenticated;
select learning_command((select v||jsonb_build_object('requestId',gen_random_uuid()) from lr_fixture where k='event'));
select is((select status from learning_sessions),'PAUSED','Heartbeat cannot resume manual pause');
select ok((select elapsed_seconds between 20 and 21 from learning_sessions),'Paused interval excluded');
update lr_fixture set v=learning_command((select v||jsonb_build_object('requestId',gen_random_uuid()) from lr_fixture where k='start'))->'session' where k='session';
select is((select v->>'status' from lr_fixture where k='session'),'ACTIVE','Explicit START resumes paused session');
select throws_ok($$select learning_command((select v||jsonb_build_object('requestId',gen_random_uuid()) from lr_fixture where k='event'))$$,'P0001','LEARNING_CONFLICT','Old generation rejected after resume');
update lr_fixture set v=learning_command((select v||jsonb_build_object('action','TAKEOVER','requestId',gen_random_uuid(),'deviceId','38000000-0000-4000-8000-000000000002') from lr_fixture where k='start'))->'session' where k='session';
select is((select v->>'device_id' from lr_fixture where k='session'),'38000000-0000-4000-8000-000000000002','Takeover moves device lease');
insert into lr_fixture select 'messageCommand',jsonb_build_object('action','MESSAGE','requestId',gen_random_uuid(),'workspaceId',v->>'workspace_id','sessionId',v->>'id','deviceId',v->>'device_id','generation',(v->>'generation')::integer,'content','I goed home.') from lr_fixture where k='session';
insert into lr_fixture select 'messageResult',learning_command(v) from lr_fixture where k='messageCommand';
select is(learning_command((select v from lr_fixture where k='messageCommand')),(select v from lr_fixture where k='messageResult'),'Duplicate send replays message and job');
select is((select count(*) from learning_messages),1::bigint,'Duplicate send persists only one user message');
select ok(not ((select v->'job' from lr_fixture where k='messageResult') ?| array['input','lease_token','model']),'Command response hides worker fields');
select throws_ok($$select learning_command((select v||jsonb_build_object('requestId',gen_random_uuid()) from lr_fixture where k='messageCommand'))$$,'P0001','LEARNING_CONFLICT','One inflight writing reply per workspace');
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000002',true);
select is((select count(*) from learning_workspaces),0::bigint,'RLS hides other owner workspaces');
select is((select count(*) from learning_messages),0::bigint,'RLS hides other owner messages');
select throws_ok($$select learning_command((select v||jsonb_build_object('requestId',gen_random_uuid()) from lr_fixture where k='messageCommand'))$$,'P0001','LEARNING_NOT_FOUND','Foreign session mutation hidden');
reset role;
set local role service_role;
insert into lr_fixture values('claim',claim_learning_job());
select is(claim_learning_job(),null::jsonb,'Live worker lease not claimed twice');
select is((select v->>'attempts' from lr_fixture where k='claim'),'1','Claim increments attempts');
select is((select v->'input'->'messages'->0->>'content' from lr_fixture where k='claim'),'I goed home.','Worker input retains original user text');
select is(finish_learning_job((select (v->>'id')::uuid from lr_fixture where k='claim'),gen_random_uuid(),null,'PROVIDER_ERROR',null,null,null,null),false,'Wrong worker token rejected');
select throws_ok($$select finish_learning_job((select (v->>'id')::uuid from lr_fixture where k='claim'),(select (v->>'lease_token')::uuid from lr_fixture where k='claim'),'{}',null,'fixture',null,1,1)$$,'P0001','LEARNING_INVALID','Invalid output rejected at DB boundary');
select ok(finish_learning_job((select (v->>'id')::uuid from lr_fixture where k='claim'),(select (v->>'lease_token')::uuid from lr_fixture where k='claim'),'{"summary":"Review past tense.","corrections":[{"original":"goed","revised":"went","reason":"Irregular verb"}],"expressions":[],"nextPrompt":"What happened next?"}',null,'fixture','resp-fixture',10,20),'Valid worker result persists');
select is(finish_learning_job((select (v->>'id')::uuid from lr_fixture where k='claim'),(select (v->>'lease_token')::uuid from lr_fixture where k='claim'),null,'PROVIDER_ERROR',null,null,null,null),false,'Late completion cannot overwrite success');
select is((select count(*) from learning_messages where user_id='18000000-0000-4000-8000-000000000001' and role='ASSISTANT'),1::bigint,'Exactly one assistant message persisted');
reset role;
select throws_ok($$insert into learning_sessions(user_id,workspace_id,status,device_id,lease_expires_at,last_seen_at,last_activity_at,timezone) values('18000000-0000-4000-8000-000000000002','28000000-0000-4000-8000-000000000001','ACTIVE',gen_random_uuid(),now(),now(),now(),'UTC')$$,'23503',null,'Composite owner FK blocks cross-user session');
update learning_sessions set last_seen_at=clock_timestamp()-interval '31 minutes',last_activity_at=clock_timestamp()-interval '31 minutes',lease_expires_at=clock_timestamp()-interval '30 minutes' where user_id='18000000-0000-4000-8000-000000000001';
set local role authenticated;
select set_config('request.jwt.claim.sub','18000000-0000-4000-8000-000000000001',true);
select learning_command((select v||jsonb_build_object('requestId',gen_random_uuid()) from lr_fixture where k='start'));
select is((select count(*) from learning_sessions),2::bigint,'Thirty minutes inactivity creates new session');
select is((select count(*) from learning_sessions where status='ENDED'),1::bigint,'Abandoned session finalized');
-- Empty new session cannot produce an invented summary.
select throws_ok($$select learning_command(jsonb_build_object('action','SUMMARY','requestId',gen_random_uuid(),'workspaceId','28000000-0000-4000-8000-000000000001','sessionId',(select id from learning_sessions where status='ACTIVE')))$$,'P0001','LEARNING_INVALID','Summary requires original session content');
insert into lr_fixture select 'summary',learning_command(jsonb_build_object('action','SUMMARY','requestId',gen_random_uuid(),'workspaceId','28000000-0000-4000-8000-000000000001','sessionId',(select v->>'id' from lr_fixture where k='session')));
reset role;
select ok(exists(select 1 from learning_private.activity_segments where user_id='18000000-0000-4000-8000-000000000001'),'UTC activity intervals retained for future daily splitting');
set local role service_role;
update lr_fixture set v=claim_learning_job() where k='claim';
select ok(finish_learning_job((select (v->>'id')::uuid from lr_fixture where k='claim'),(select (v->>'lease_token')::uuid from lr_fixture where k='claim'),jsonb_build_object('summary',repeat('s',2000),'corrections','[]'::jsonb,'expressions',(select jsonb_agg(jsonb_build_object('phrase',repeat('p',200),'meaning',repeat('m',600),'example',repeat('e',1000))) from generate_series(1,10)),'nextPrompt',repeat('n',1000)),null,'fixture',null,null,null),'Schema-bounded output above 20000 chars and missing usage completes');
select ok((select input_tokens is null and output_tokens is null from learning_ai_jobs where id=(select (v->>'id')::uuid from lr_fixture where k='claim')),'Absent provider usage remains null');
set local role authenticated;
select is(learning_command(jsonb_build_object('action','SUMMARY','requestId',gen_random_uuid(),'workspaceId','28000000-0000-4000-8000-000000000001','sessionId',(select v->>'id' from lr_fixture where k='session')))->'job'->>'id',(select v->'job'->>'id' from lr_fixture where k='summary'),'Identical source summary reuses succeeded job');
select is((select count(*) from learning_messages where user_id='18000000-0000-4000-8000-000000000001' and role='ASSISTANT'),1::bigint,'Summary does not duplicate conversation replies');
-- Provider failure and retries preserve the original user message, with a hard attempt ceiling.
insert into lr_fixture select 'retryMessage',learning_command(jsonb_build_object('action','MESSAGE','requestId',gen_random_uuid(),'workspaceId',workspace_id,'sessionId',id,'deviceId',device_id,'generation',generation,'content','I am trying again.')) from learning_sessions where status='ACTIVE';
reset role;
set local role service_role;
update lr_fixture set v=claim_learning_job() where k='claim';
select ok(finish_learning_job((select (v->>'id')::uuid from lr_fixture where k='claim'),(select (v->>'lease_token')::uuid from lr_fixture where k='claim'),null,'PROVIDER_ERROR',null,null,null,null),'Provider failure persisted');
set local role authenticated;
select lives_ok($$select learning_command(jsonb_build_object('action','RETRY','requestId',gen_random_uuid(),'jobId',(select v->'job'->>'id' from lr_fixture where k='retryMessage')))$$,'Failed job can be retried');
select is((select count(*) from learning_messages where role='USER'),2::bigint,'Retry does not duplicate user text');
reset role;
set local role service_role;
update lr_fixture set v=claim_learning_job() where k='claim';
update learning_ai_jobs set lease_expires_at=clock_timestamp()-interval '1 second' where id=(select (v->>'id')::uuid from lr_fixture where k='claim');
select is(finish_learning_job((select (v->>'id')::uuid from lr_fixture where k='claim'),(select (v->>'lease_token')::uuid from lr_fixture where k='claim'),null,'PROVIDER_ERROR',null,null,null,null),false,'Expired worker lease cannot finish');
update lr_fixture set v=claim_learning_job() where k='claim';
select is((select v->>'attempts' from lr_fixture where k='claim'),'3','Expired job reclaims final attempt');
update learning_ai_jobs set lease_expires_at=clock_timestamp()-interval '1 second' where id=(select (v->>'id')::uuid from lr_fixture where k='claim');
select is(claim_learning_job(),null::jsonb,'Three exhausted attempts are not reclaimed');
set local role authenticated;
select throws_ok($$select learning_command(jsonb_build_object('action','RETRY','requestId',gen_random_uuid(),'jobId',(select v->'job'->>'id' from lr_fixture where k='retryMessage')))$$,'P0001','LEARNING_CONFLICT','User cannot bypass three-attempt ceiling');
reset role;
select * from finish();
rollback;
