// Generated by pnpm db:types. Do not edit manually.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      ai_jobs: {
        Row: {
          attempts: number
          created_at: string
          error_code: string | null
          id: string
          input: Json
          input_tokens: number | null
          kind: string
          lease_expires_at: string | null
          lease_token: string | null
          model: string | null
          output_tokens: number | null
          provider_response_id: string | null
          resource_id: string
          result: Json | null
          source_revision: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          error_code?: string | null
          id?: string
          input: Json
          input_tokens?: number | null
          kind: string
          lease_expires_at?: string | null
          lease_token?: string | null
          model?: string | null
          output_tokens?: number | null
          provider_response_id?: string | null
          resource_id: string
          result?: Json | null
          source_revision: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          attempts?: number
          created_at?: string
          error_code?: string | null
          id?: string
          input?: Json
          input_tokens?: number | null
          kind?: string
          lease_expires_at?: string | null
          lease_token?: string | null
          model?: string | null
          output_tokens?: number | null
          provider_response_id?: string | null
          resource_id?: string
          result?: Json | null
          source_revision?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_jobs_resource_id_user_id_fkey"
            columns: ["resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      availability_rules: {
        Row: {
          available_minutes: number
          created_at: string
          id: string
          iso_weekday: number
          updated_at: string
          user_id: string
        }
        Insert: {
          available_minutes: number
          created_at?: string
          id?: string
          iso_weekday: number
          updated_at?: string
          user_id: string
        }
        Update: {
          available_minutes?: number
          created_at?: string
          id?: string
          iso_weekday?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      goals: {
        Row: {
          created_at: string
          id: string
          mode: Database["public"]["Enums"]["plan_mode"]
          preferred_daily_workload: number | null
          resource_id: string
          start_date: string
          status: Database["public"]["Enums"]["plan_status"]
          target_date: string | null
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          mode?: Database["public"]["Enums"]["plan_mode"]
          preferred_daily_workload?: number | null
          resource_id: string
          start_date: string
          status?: Database["public"]["Enums"]["plan_status"]
          target_date?: string | null
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          mode?: Database["public"]["Enums"]["plan_mode"]
          preferred_daily_workload?: number | null
          resource_id?: string
          start_date?: string
          status?: Database["public"]["Enums"]["plan_status"]
          target_date?: string | null
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "goals_resource_id_user_id_fkey"
            columns: ["resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      learner_profiles: {
        Row: {
          average_session_minutes: number | null
          completion_rate: number | null
          created_at: string
          daily_learning_minutes: number | null
          notify_at: string | null
          notify_last_sent_on: string | null
          pages_per_minute: number | null
          preferred_time: string | null
          speed_sample_count: number
          timezone: string
          units_per_hour: number | null
          updated_at: string
          user_id: string
          workload_multiplier: number
        }
        Insert: {
          average_session_minutes?: number | null
          completion_rate?: number | null
          created_at?: string
          daily_learning_minutes?: number | null
          notify_at?: string | null
          notify_last_sent_on?: string | null
          pages_per_minute?: number | null
          preferred_time?: string | null
          speed_sample_count?: number
          timezone?: string
          units_per_hour?: number | null
          updated_at?: string
          user_id: string
          workload_multiplier?: number
        }
        Update: {
          average_session_minutes?: number | null
          completion_rate?: number | null
          created_at?: string
          daily_learning_minutes?: number | null
          notify_at?: string | null
          notify_last_sent_on?: string | null
          pages_per_minute?: number | null
          preferred_time?: string | null
          speed_sample_count?: number
          timezone?: string
          units_per_hour?: number | null
          updated_at?: string
          user_id?: string
          workload_multiplier?: number
        }
        Relationships: []
      }
      learning_ai_jobs: {
        Row: {
          attempts: number
          created_at: string
          error_code: string | null
          id: string
          input: Json
          input_tokens: number | null
          kind: string
          lease_expires_at: string | null
          lease_token: string | null
          model: string | null
          output: Json | null
          output_tokens: number | null
          provider_response_id: string | null
          session_id: string | null
          status: string
          updated_at: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          error_code?: string | null
          id?: string
          input: Json
          input_tokens?: number | null
          kind: string
          lease_expires_at?: string | null
          lease_token?: string | null
          model?: string | null
          output?: Json | null
          output_tokens?: number | null
          provider_response_id?: string | null
          session_id?: string | null
          status?: string
          updated_at?: string
          user_id: string
          workspace_id: string
        }
        Update: {
          attempts?: number
          created_at?: string
          error_code?: string | null
          id?: string
          input?: Json
          input_tokens?: number | null
          kind?: string
          lease_expires_at?: string | null
          lease_token?: string | null
          model?: string | null
          output?: Json | null
          output_tokens?: number | null
          provider_response_id?: string | null
          session_id?: string | null
          status?: string
          updated_at?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_ai_jobs_session_id_workspace_id_user_id_fkey"
            columns: ["session_id", "workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_sessions"
            referencedColumns: ["id", "workspace_id", "user_id"]
          },
          {
            foreignKeyName: "learning_ai_jobs_workspace_id_user_id_fkey"
            columns: ["workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_workspaces"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      learning_expressions: {
        Row: {
          created_at: string
          due_on: string
          end_page: number | null
          example: string | null
          examples: string[]
          id: string
          kind: string
          last_reviewed_on: string | null
          lease_expires_at: string | null
          lease_token: string | null
          lookup_attempts: number
          lookup_status: string
          meaning: string | null
          phrase: string
          resource_id: string | null
          review_count: number
          review_step: number
          source_workspace_id: string | null
          start_page: number | null
          unit_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          due_on: string
          end_page?: number | null
          example?: string | null
          examples?: string[]
          id?: string
          kind?: string
          last_reviewed_on?: string | null
          lease_expires_at?: string | null
          lease_token?: string | null
          lookup_attempts?: number
          lookup_status?: string
          meaning?: string | null
          phrase: string
          resource_id?: string | null
          review_count?: number
          review_step?: number
          source_workspace_id?: string | null
          start_page?: number | null
          unit_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          due_on?: string
          end_page?: number | null
          example?: string | null
          examples?: string[]
          id?: string
          kind?: string
          last_reviewed_on?: string | null
          lease_expires_at?: string | null
          lease_token?: string | null
          lookup_attempts?: number
          lookup_status?: string
          meaning?: string | null
          phrase?: string
          resource_id?: string | null
          review_count?: number
          review_step?: number
          source_workspace_id?: string | null
          start_page?: number | null
          unit_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_expressions_resource_fk"
            columns: ["resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id", "user_id"]
          },
          {
            foreignKeyName: "learning_expressions_source_workspace_id_fkey"
            columns: ["source_workspace_id"]
            isOneToOne: false
            referencedRelation: "learning_workspaces"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "learning_expressions_unit_fk"
            columns: ["unit_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resource_units"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
        ]
      }
      learning_messages: {
        Row: {
          content: string
          created_at: string
          id: string
          job_id: string | null
          role: string
          session_id: string | null
          user_id: string
          workspace_id: string
        }
        Insert: {
          content: string
          created_at?: string
          id?: string
          job_id?: string | null
          role: string
          session_id?: string | null
          user_id: string
          workspace_id: string
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          job_id?: string | null
          role?: string
          session_id?: string | null
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_messages_job_id_workspace_id_user_id_fkey"
            columns: ["job_id", "workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_ai_jobs"
            referencedColumns: ["id", "workspace_id", "user_id"]
          },
          {
            foreignKeyName: "learning_messages_session_id_workspace_id_user_id_fkey"
            columns: ["session_id", "workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_sessions"
            referencedColumns: ["id", "workspace_id", "user_id"]
          },
          {
            foreignKeyName: "learning_messages_workspace_id_user_id_fkey"
            columns: ["workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_workspaces"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      learning_sessions: {
        Row: {
          device_id: string
          elapsed_seconds: number
          ended_at: string | null
          generation: number
          id: string
          last_activity_at: string
          last_seen_at: string
          lease_expires_at: string
          pause_reason: string | null
          started_at: string
          status: string
          timezone: string
          updated_at: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          device_id: string
          elapsed_seconds?: number
          ended_at?: string | null
          generation?: number
          id?: string
          last_activity_at: string
          last_seen_at: string
          lease_expires_at: string
          pause_reason?: string | null
          started_at?: string
          status: string
          timezone: string
          updated_at?: string
          user_id: string
          workspace_id: string
        }
        Update: {
          device_id?: string
          elapsed_seconds?: number
          ended_at?: string | null
          generation?: number
          id?: string
          last_activity_at?: string
          last_seen_at?: string
          lease_expires_at?: string
          pause_reason?: string | null
          started_at?: string
          status?: string
          timezone?: string
          updated_at?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_sessions_workspace_id_user_id_fkey"
            columns: ["workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_workspaces"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      learning_speech: {
        Row: {
          attempts: number
          audio_deleted_at: string | null
          content_sha256: string | null
          created_at: string
          duration_seconds: number | null
          edited_text: string | null
          error_code: string | null
          expires_at: string
          feedback: Json | null
          file_size: number | null
          id: string
          input: Json
          keep_audio: boolean
          kind: string
          lease_expires_at: string | null
          lease_token: string | null
          mime_type: string | null
          original_text: string
          reference_text: string
          session_id: string | null
          status: string
          storage_path: string | null
          updated_at: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          attempts?: number
          audio_deleted_at?: string | null
          content_sha256?: string | null
          created_at?: string
          duration_seconds?: number | null
          edited_text?: string | null
          error_code?: string | null
          expires_at?: string
          feedback?: Json | null
          file_size?: number | null
          id: string
          input?: Json
          keep_audio?: boolean
          kind: string
          lease_expires_at?: string | null
          lease_token?: string | null
          mime_type?: string | null
          original_text?: string
          reference_text?: string
          session_id?: string | null
          status: string
          storage_path?: string | null
          updated_at?: string
          user_id: string
          workspace_id: string
        }
        Update: {
          attempts?: number
          audio_deleted_at?: string | null
          content_sha256?: string | null
          created_at?: string
          duration_seconds?: number | null
          edited_text?: string | null
          error_code?: string | null
          expires_at?: string
          feedback?: Json | null
          file_size?: number | null
          id?: string
          input?: Json
          keep_audio?: boolean
          kind?: string
          lease_expires_at?: string | null
          lease_token?: string | null
          mime_type?: string | null
          original_text?: string
          reference_text?: string
          session_id?: string | null
          status?: string
          storage_path?: string | null
          updated_at?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_speech_session_id_workspace_id_user_id_fkey"
            columns: ["session_id", "workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_sessions"
            referencedColumns: ["id", "workspace_id", "user_id"]
          },
          {
            foreignKeyName: "learning_speech_workspace_id_user_id_fkey"
            columns: ["workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_workspaces"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      learning_video_notes: {
        Row: {
          content: string
          created_at: string
          id: string
          position_seconds: number
          user_id: string
          workspace_id: string
        }
        Insert: {
          content: string
          created_at?: string
          id: string
          position_seconds: number
          user_id: string
          workspace_id: string
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          position_seconds?: number
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_video_notes_workspace_id_user_id_fkey"
            columns: ["workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_videos"
            referencedColumns: ["workspace_id", "user_id"]
          },
        ]
      }
      learning_video_visits: {
        Row: {
          created_at: string
          from_seconds: number
          id: string
          rate: number
          session_id: string
          to_seconds: number
          user_id: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          from_seconds: number
          id?: string
          rate: number
          session_id: string
          to_seconds: number
          user_id: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          from_seconds?: number
          id?: string
          rate?: number
          session_id?: string
          to_seconds?: number
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_video_visits_session_id_workspace_id_user_id_fkey"
            columns: ["session_id", "workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_sessions"
            referencedColumns: ["id", "workspace_id", "user_id"]
          },
          {
            foreignKeyName: "learning_video_visits_workspace_id_user_id_fkey"
            columns: ["workspace_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_videos"
            referencedColumns: ["workspace_id", "user_id"]
          },
        ]
      }
      learning_videos: {
        Row: {
          archived: boolean
          context_end: number
          context_start: number
          duration_seconds: number | null
          favorite: boolean
          position_seconds: number
          start_seconds: number
          transcript: string
          transcript_version: number
          updated_at: string
          user_id: string
          video_id: string
          workspace_id: string
        }
        Insert: {
          archived?: boolean
          context_end?: number
          context_start?: number
          duration_seconds?: number | null
          favorite?: boolean
          position_seconds?: number
          start_seconds?: number
          transcript?: string
          transcript_version?: number
          updated_at?: string
          user_id: string
          video_id: string
          workspace_id: string
        }
        Update: {
          archived?: boolean
          context_end?: number
          context_start?: number
          duration_seconds?: number | null
          favorite?: boolean
          position_seconds?: number
          start_seconds?: number
          transcript?: string
          transcript_version?: number
          updated_at?: string
          user_id?: string
          video_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_videos_workspace_id_user_id_fkey"
            columns: ["workspace_id", "user_id"]
            isOneToOne: true
            referencedRelation: "learning_workspaces"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      learning_workspaces: {
        Row: {
          created_at: string
          draft: string
          draft_version: number
          id: string
          kind: string
          prompt: string
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          draft?: string
          draft_version?: number
          id?: string
          kind: string
          prompt?: string
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          draft?: string
          draft_version?: number
          id?: string
          kind?: string
          prompt?: string
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      material_imports: {
        Row: {
          attempts: number
          context: Json
          created_at: string
          error_code: string | null
          id: string
          input: string
          lease_expires_at: string | null
          lease_token: string | null
          page_title: string | null
          result: Json | null
          source_url: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          attempts?: number
          context?: Json
          created_at?: string
          error_code?: string | null
          id?: string
          input: string
          lease_expires_at?: string | null
          lease_token?: string | null
          page_title?: string | null
          result?: Json | null
          source_url: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          attempts?: number
          context?: Json
          created_at?: string
          error_code?: string | null
          id?: string
          input?: string
          lease_expires_at?: string | null
          lease_token?: string | null
          page_title?: string | null
          result?: Json | null
          source_url?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      pdf_imports: {
        Row: {
          attempts: number
          confirmation_current_page: number | null
          confirmation_title: string | null
          content_sha256: string
          created_at: string
          error_code: string | null
          file_size: number
          filename: string
          id: string
          lease_expires_at: string | null
          lease_token: string | null
          resource_id: string | null
          result: Json | null
          status: string
          storage_path: string
          updated_at: string
          user_id: string
        }
        Insert: {
          attempts?: number
          confirmation_current_page?: number | null
          confirmation_title?: string | null
          content_sha256: string
          created_at?: string
          error_code?: string | null
          file_size: number
          filename: string
          id: string
          lease_expires_at?: string | null
          lease_token?: string | null
          resource_id?: string | null
          result?: Json | null
          status?: string
          storage_path: string
          updated_at?: string
          user_id: string
        }
        Update: {
          attempts?: number
          confirmation_current_page?: number | null
          confirmation_title?: string | null
          content_sha256?: string
          created_at?: string
          error_code?: string | null
          file_size?: number
          filename?: string
          id?: string
          lease_expires_at?: string | null
          lease_token?: string | null
          resource_id?: string | null
          result?: Json | null
          status?: string
          storage_path?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pdf_imports_resource_id_user_id_fkey"
            columns: ["resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      plans: {
        Row: {
          created_at: string
          forecast_date: string | null
          goal_id: string
          id: string
          minutes_per_page: number
          mode: Database["public"]["Enums"]["plan_mode"]
          preferred_daily_workload: number | null
          resource_id: string
          start_date: string
          status: Database["public"]["Enums"]["plan_status"]
          target_date: string | null
          timezone: string
          updated_at: string
          user_id: string
          version: number
        }
        Insert: {
          created_at?: string
          forecast_date?: string | null
          goal_id: string
          id?: string
          minutes_per_page?: number
          mode?: Database["public"]["Enums"]["plan_mode"]
          preferred_daily_workload?: number | null
          resource_id: string
          start_date: string
          status?: Database["public"]["Enums"]["plan_status"]
          target_date?: string | null
          timezone?: string
          updated_at?: string
          user_id: string
          version?: number
        }
        Update: {
          created_at?: string
          forecast_date?: string | null
          goal_id?: string
          id?: string
          minutes_per_page?: number
          mode?: Database["public"]["Enums"]["plan_mode"]
          preferred_daily_workload?: number | null
          resource_id?: string
          start_date?: string
          status?: Database["public"]["Enums"]["plan_status"]
          target_date?: string | null
          timezone?: string
          updated_at?: string
          user_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "plans_goal_id_resource_id_user_id_fkey"
            columns: ["goal_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "goals"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
          {
            foreignKeyName: "plans_resource_id_user_id_fkey"
            columns: ["resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      progress_events: {
        Row: {
          completed_at: string | null
          completed_workload: number
          created_at: string
          difficulty_feedback: number | null
          duration_minutes: number | null
          end_page: number | null
          event_type: Database["public"]["Enums"]["progress_event_type"]
          id: string
          idempotency_key: string
          memo: string | null
          resource_id: string
          session_id: string | null
          start_page: number | null
          started_at: string | null
          study_date: string
          timezone: string
          unit_id: string | null
          user_id: string
          voids_event_id: string | null
        }
        Insert: {
          completed_at?: string | null
          completed_workload: number
          created_at?: string
          difficulty_feedback?: number | null
          duration_minutes?: number | null
          end_page?: number | null
          event_type?: Database["public"]["Enums"]["progress_event_type"]
          id?: string
          idempotency_key: string
          memo?: string | null
          resource_id: string
          session_id?: string | null
          start_page?: number | null
          started_at?: string | null
          study_date: string
          timezone?: string
          unit_id?: string | null
          user_id: string
          voids_event_id?: string | null
        }
        Update: {
          completed_at?: string | null
          completed_workload?: number
          created_at?: string
          difficulty_feedback?: number | null
          duration_minutes?: number | null
          end_page?: number | null
          event_type?: Database["public"]["Enums"]["progress_event_type"]
          id?: string
          idempotency_key?: string
          memo?: string | null
          resource_id?: string
          session_id?: string | null
          start_page?: number | null
          started_at?: string | null
          study_date?: string
          timezone?: string
          unit_id?: string | null
          user_id?: string
          voids_event_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "progress_events_resource_id_user_id_fkey"
            columns: ["resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id", "user_id"]
          },
          {
            foreignKeyName: "progress_events_session_id_resource_id_user_id_fkey"
            columns: ["session_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "schedule_sessions"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
          {
            foreignKeyName: "progress_events_unit_id_resource_id_user_id_fkey"
            columns: ["unit_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resource_units"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
          {
            foreignKeyName: "progress_events_voids_event_id_resource_id_user_id_fkey"
            columns: ["voids_event_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "progress_events"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
        ]
      }
      progress_submissions: {
        Row: {
          created_at: string
          id: string
          idempotency_key: string
          request: Json
          resource_id: string
          result: Json
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          idempotency_key: string
          request: Json
          resource_id: string
          result: Json
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          idempotency_key?: string
          request?: Json
          resource_id?: string
          result?: Json
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "progress_submissions_resource_id_user_id_fkey"
            columns: ["resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          failure_count: number
          id: string
          p256dh: string
          timezone: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          failure_count?: number
          id?: string
          p256dh: string
          timezone?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          failure_count?: number
          id?: string
          p256dh?: string
          timezone?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      replan_runs: {
        Row: {
          after_snapshot: Json
          before_snapshot: Json
          created_at: string
          from_version: number
          id: string
          idempotency_key: string
          plan_id: string
          policy_version: string
          reason: Json
          resource_id: string
          status: Database["public"]["Enums"]["replan_status"]
          to_version: number
          user_id: string
        }
        Insert: {
          after_snapshot?: Json
          before_snapshot?: Json
          created_at?: string
          from_version: number
          id?: string
          idempotency_key: string
          plan_id: string
          policy_version: string
          reason: Json
          resource_id: string
          status: Database["public"]["Enums"]["replan_status"]
          to_version: number
          user_id: string
        }
        Update: {
          after_snapshot?: Json
          before_snapshot?: Json
          created_at?: string
          from_version?: number
          id?: string
          idempotency_key?: string
          plan_id?: string
          policy_version?: string
          reason?: Json
          resource_id?: string
          status?: Database["public"]["Enums"]["replan_status"]
          to_version?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "replan_runs_plan_id_resource_id_user_id_fkey"
            columns: ["plan_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
        ]
      }
      resource_units: {
        Row: {
          ai_confidence: number | null
          created_at: string
          difficulty: number | null
          end_page: number | null
          estimated_minutes: number | null
          id: string
          importance: number | null
          parent_unit_id: string | null
          resource_id: string
          sequence: number
          start_page: number | null
          title: string
          unit_type: Database["public"]["Enums"]["unit_type"]
          updated_at: string
          user_id: string
          workload: number | null
        }
        Insert: {
          ai_confidence?: number | null
          created_at?: string
          difficulty?: number | null
          end_page?: number | null
          estimated_minutes?: number | null
          id?: string
          importance?: number | null
          parent_unit_id?: string | null
          resource_id: string
          sequence: number
          start_page?: number | null
          title: string
          unit_type: Database["public"]["Enums"]["unit_type"]
          updated_at?: string
          user_id: string
          workload?: number | null
        }
        Update: {
          ai_confidence?: number | null
          created_at?: string
          difficulty?: number | null
          end_page?: number | null
          estimated_minutes?: number | null
          id?: string
          importance?: number | null
          parent_unit_id?: string | null
          resource_id?: string
          sequence?: number
          start_page?: number | null
          title?: string
          unit_type?: Database["public"]["Enums"]["unit_type"]
          updated_at?: string
          user_id?: string
          workload?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "resource_units_parent_unit_id_resource_id_user_id_fkey"
            columns: ["parent_unit_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resource_units"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
          {
            foreignKeyName: "resource_units_resource_id_user_id_fkey"
            columns: ["resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resources"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      resources: {
        Row: {
          author: string | null
          cover_url: string | null
          created_at: string
          id: string
          initial_completed_workload: number
          isbn: string | null
          progress_version: number
          publisher: string | null
          replan_required: boolean
          source: string
          source_id: string | null
          status: Database["public"]["Enums"]["resource_status"]
          title: string
          total_pages: number | null
          total_units: number | null
          type: Database["public"]["Enums"]["resource_type"]
          unit_label: string | null
          updated_at: string
          user_id: string
          workload_unit: Database["public"]["Enums"]["workload_unit"]
        }
        Insert: {
          author?: string | null
          cover_url?: string | null
          created_at?: string
          id?: string
          initial_completed_workload?: number
          isbn?: string | null
          progress_version?: number
          publisher?: string | null
          replan_required?: boolean
          source?: string
          source_id?: string | null
          status?: Database["public"]["Enums"]["resource_status"]
          title: string
          total_pages?: number | null
          total_units?: number | null
          type: Database["public"]["Enums"]["resource_type"]
          unit_label?: string | null
          updated_at?: string
          user_id: string
          workload_unit?: Database["public"]["Enums"]["workload_unit"]
        }
        Update: {
          author?: string | null
          cover_url?: string | null
          created_at?: string
          id?: string
          initial_completed_workload?: number
          isbn?: string | null
          progress_version?: number
          publisher?: string | null
          replan_required?: boolean
          source?: string
          source_id?: string | null
          status?: Database["public"]["Enums"]["resource_status"]
          title?: string
          total_pages?: number | null
          total_units?: number | null
          type?: Database["public"]["Enums"]["resource_type"]
          unit_label?: string | null
          updated_at?: string
          user_id?: string
          workload_unit?: Database["public"]["Enums"]["workload_unit"]
        }
        Relationships: []
      }
      schedule_sessions: {
        Row: {
          created_at: string
          end_page: number | null
          estimated_minutes: number | null
          id: string
          is_locked: boolean
          plan_id: string
          plan_version: number
          planned_workload: number
          replan_run_id: string | null
          resource_id: string
          start_page: number | null
          status: Database["public"]["Enums"]["session_status"]
          study_date: string
          unit_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          end_page?: number | null
          estimated_minutes?: number | null
          id?: string
          is_locked?: boolean
          plan_id: string
          plan_version?: number
          planned_workload: number
          replan_run_id?: string | null
          resource_id: string
          start_page?: number | null
          status?: Database["public"]["Enums"]["session_status"]
          study_date: string
          unit_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          end_page?: number | null
          estimated_minutes?: number | null
          id?: string
          is_locked?: boolean
          plan_id?: string
          plan_version?: number
          planned_workload?: number
          replan_run_id?: string | null
          resource_id?: string
          start_page?: number | null
          status?: Database["public"]["Enums"]["session_status"]
          study_date?: string
          unit_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "schedule_sessions_plan_id_resource_id_user_id_fkey"
            columns: ["plan_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
          {
            foreignKeyName: "schedule_sessions_replan_run_id_plan_id_resource_id_user_i_fkey"
            columns: ["replan_run_id", "plan_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "replan_runs"
            referencedColumns: ["id", "plan_id", "resource_id", "user_id"]
          },
          {
            foreignKeyName: "schedule_sessions_unit_id_resource_id_user_id_fkey"
            columns: ["unit_id", "resource_id", "user_id"]
            isOneToOne: false
            referencedRelation: "resource_units"
            referencedColumns: ["id", "resource_id", "user_id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      begin_pdf_import: {
        Args: {
          p_content_sha256: string
          p_file_size: number
          p_filename: string
          p_id: string
        }
        Returns: Json
      }
      begin_speech_upload: {
        Args: {
          p_content_sha256: string
          p_file_size: number
          p_id: string
          p_mime_type: string
          p_reference_text: string
          p_session_id: string
          p_workspace_id: string
        }
        Returns: Json
      }
      checkpoint_speech_prompt: {
        Args: {
          p_job_id: string
          p_lease_token: string
          p_meaning: string
          p_reference_text: string
        }
        Returns: boolean
      }
      claim_ai_job: { Args: never; Returns: Json }
      claim_due_notifications: {
        Args: { p_limit?: number }
        Returns: {
          auth: string
          due_pages: number
          endpoint: string
          goal_minutes: number
          p256dh: string
          subscription_id: string
          user_id: string
        }[]
      }
      claim_expression_lookup: { Args: never; Returns: Json }
      claim_learning_job: { Args: never; Returns: Json }
      claim_material_import: { Args: never; Returns: Json }
      claim_pdf_import: { Args: never; Returns: Json }
      claim_speech_job: { Args: never; Returns: Json }
      confirm_pdf_import: {
        Args: { p_current_page: number; p_id: string; p_title: string }
        Returns: string
      }
      create_initial_book_plan: {
        Args: {
          p_expected_completed: number
          p_expected_total: number
          p_forecast: string
          p_options: Json
          p_resource_id: string
          p_sessions: Json
        }
        Returns: string
      }
      create_unit_material: { Args: { p_input: Json }; Returns: string }
      discard_pdf_import: { Args: { p_id: string }; Returns: boolean }
      enqueue_ai_job: {
        Args: {
          p_input: Json
          p_kind: string
          p_resource_id: string
          p_source_revision: string
        }
        Returns: string
      }
      finish_ai_job: {
        Args: {
          p_error_code: string
          p_input_tokens: number
          p_job_id: string
          p_lease_token: string
          p_model: string
          p_output_tokens: number
          p_provider_response_id: string
          p_result: Json
        }
        Returns: boolean
      }
      finish_expression_lookup: {
        Args: {
          p_examples: string[]
          p_failed: boolean
          p_id: string
          p_lease_token: string
          p_meaning: string
        }
        Returns: boolean
      }
      finish_learning_job: {
        Args: {
          p_error_code: string
          p_input_tokens: number
          p_job_id: string
          p_lease_token: string
          p_model: string
          p_output: Json
          p_output_tokens: number
          p_provider_response_id: string
        }
        Returns: boolean
      }
      finish_material_import: {
        Args: {
          p_error_code: string
          p_id: string
          p_lease_token: string
          p_result: Json
        }
        Returns: boolean
      }
      finish_notification: {
        Args: { p_gone: boolean; p_subscription_id: string }
        Returns: undefined
      }
      finish_pdf_import: {
        Args: {
          p_error_code: string
          p_id: string
          p_lease_token: string
          p_result: Json
        }
        Returns: boolean
      }
      finish_speech_cleanup: { Args: { p_id: string }; Returns: boolean }
      finish_speech_job: {
        Args: {
          p_error_code: string
          p_job_id: string
          p_lease_token: string
          p_output: Json
        }
        Returns: boolean
      }
      learning_command: { Args: { p_command: Json }; Returns: Json }
      learning_daily_minutes: {
        Args: { p_from: string; p_to: string }
        Returns: {
          minutes: number
          study_date: string
        }[]
      }
      learning_speech_command: { Args: { p_command: Json }; Returns: Json }
      learning_video_command: { Args: { p_command: Json }; Returns: Json }
      plan_unit_material: {
        Args: { p_options: Json; p_resource_id: string }
        Returns: Json
      }
      queue_pdf_import: { Args: { p_id: string }; Returns: Json }
      queue_speech_recording: { Args: { p_id: string }; Returns: Json }
      record_expression_review: {
        Args: {
          p_due_on: string
          p_id: string
          p_step: number
          p_today: string
        }
        Returns: {
          created_at: string
          due_on: string
          end_page: number | null
          example: string | null
          examples: string[]
          id: string
          kind: string
          last_reviewed_on: string | null
          lease_expires_at: string | null
          lease_token: string | null
          lookup_attempts: number
          lookup_status: string
          meaning: string | null
          phrase: string
          resource_id: string | null
          review_count: number
          review_step: number
          source_workspace_id: string | null
          start_page: number | null
          unit_id: string | null
          updated_at: string
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "learning_expressions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      replace_availability_rules: {
        Args: { p_rules: Json }
        Returns: undefined
      }
      replan_unit_plan: {
        Args: { p_dry_run?: boolean; p_resource_id: string }
        Returns: Json
      }
      retry_pdf_import: { Args: { p_id: string }; Returns: Json }
      speech_audio_path: { Args: { p_id: string }; Returns: Json }
      speech_cleanup_candidates: { Args: never; Returns: Json }
      speech_storage_allowed: {
        Args: { p_metadata: Json; p_name: string; p_write: boolean }
        Returns: boolean
      }
      submit_book_progress: {
        Args: {
          p_as_of_date: string
          p_candidate: Json
          p_expected_initial: number
          p_expected_sessions: Json
          p_expected_total: number
          p_request: Json
          p_resource_id: string
        }
        Returns: Json
      }
      submit_unit_progress: {
        Args: { p_request: Json; p_resource_id: string }
        Returns: Json
      }
      youtube_connection_command: { Args: { p_command: Json }; Returns: Json }
    }
    Enums: {
      plan_mode: "DEADLINE" | "PACE" | "BALANCED"
      plan_status: "ACTIVE" | "PAUSED" | "COMPLETED" | "ARCHIVED"
      progress_event_type: "LEARNING" | "REVIEW" | "VOID"
      replan_status: "APPLIED" | "SKIPPED" | "FAILED"
      resource_status: "ACTIVE" | "COMPLETED" | "ARCHIVED"
      resource_type: "BOOK" | "PDF" | "COURSE" | "VIDEO" | "CUSTOM"
      session_status: "PLANNED" | "IN_PROGRESS" | "COMPLETED" | "SKIPPED"
      unit_type:
        | "CHAPTER"
        | "SECTION"
        | "UNIT"
        | "PAGE_RANGE"
        | "LECTURE"
        | "VIDEO"
        | "CUSTOM"
      workload_unit: "PAGE" | "UNIT" | "MINUTE"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      plan_mode: ["DEADLINE", "PACE", "BALANCED"],
      plan_status: ["ACTIVE", "PAUSED", "COMPLETED", "ARCHIVED"],
      progress_event_type: ["LEARNING", "REVIEW", "VOID"],
      replan_status: ["APPLIED", "SKIPPED", "FAILED"],
      resource_status: ["ACTIVE", "COMPLETED", "ARCHIVED"],
      resource_type: ["BOOK", "PDF", "COURSE", "VIDEO", "CUSTOM"],
      session_status: ["PLANNED", "IN_PROGRESS", "COMPLETED", "SKIPPED"],
      unit_type: [
        "CHAPTER",
        "SECTION",
        "UNIT",
        "PAGE_RANGE",
        "LECTURE",
        "VIDEO",
        "CUSTOM",
      ],
      workload_unit: ["PAGE", "UNIT", "MINUTE"],
    },
  },
} as const

