import { spawnSync } from 'node:child_process';
import { writeFileSync, readFileSync } from 'node:fs';

const result = spawnSync('supabase', ['gen', 'types', 'typescript', '--local', '--schema', 'public'], {
  encoding: 'utf8', windowsHide: true,
});
if (result.error || result.status !== 0 || !result.stdout.includes('export type Database')) {
  console.error('Type generation failed:', result.error?.message ?? result.stderr);
  process.exit(1);
}
const destination = new URL('../packages/shared/src/database.types.ts', import.meta.url);
const content = '// Generated by pnpm db:types. Do not edit manually.\n' + result.stdout.replaceAll('\r\n', '\n');
if (process.argv.includes('--check')) {
  if (readFileSync(destination, 'utf8').replaceAll('\r\n', '\n') !== content) {
    console.error('Database types are stale. Run pnpm db:types.');
    process.exit(1);
  }
  console.log('Database types match the local schema.');
} else {
  writeFileSync(destination, content, 'utf8');
  console.log('Generated packages/shared/src/database.types.ts');
}
